export const dogBreeds = [
  { name: 'Affenpinscher' },
  { name: 'Afgano' },
  { name: 'Akita japonés' },
  { name: 'Basenji' },
  { name: 'Basset Azul de Gascuña' },
  { name: 'Basset Grifón vandeano (grande)' },
  { name: 'Basset Grifón vandeano (pequeño)' },
  { name: 'Basset Hound' },
  { name: 'Basset leonado de Bretaña' },
  { name: 'Beagle' },
  { name: 'Beauceron' },
  { name: 'Bedlington Terrier' },
  { name: 'Bergamasco' },
  { name: 'Bichón Boloñés' },
  { name: 'Bichón frisé' },
  { name: 'Bloodhound' },
  { name: 'Bobtail (antiguo perro pastor inglés)' },
  { name: 'Border collie' },
  { name: 'Border terrier' },
  { name: 'Borzoi' },
  { name: 'Boston Terrier' },
  { name: 'Bóxer' },
  { name: 'Boyero de Berna' },
  { name: 'Boyero de Flandes' },
  { name: 'Bracco italiano' },
  { name: 'Braco alemán de pelo corto' },
  { name: 'Braco alemán de pelo duro' },
  { name: 'Braco de Weimar (de pelo corto y suave)' },
  { name: 'Braco húngaro' },
  { name: 'Braco húngaro de pelo duro' },
  { name: 'Bretón' },
  { name: 'Buhund noruego' },
  { name: 'Bull Terrier' },
  { name: 'Bull Terrier miniatura' },
  { name: 'Bulldog' },
  { name: 'Bulldog francés' },
  { name: 'Bullmastiff' },
  { name: 'Cairn Terrier' },
  { name: 'Caniche enano' },
  { name: 'Caniche grande' },
  { name: 'Caniche toy' },
  { name: 'Carlino' },
  { name: 'Cavalier King Charles Spaniel' },
  { name: 'Cazador de alces noruego (elkhound noruego)' },
  { name: 'Chihuahua (de pelo largo)' },
  { name: 'Chihuahua (de pelo suave)' },
  { name: 'Chin japonés' },
  { name: 'Chow chow (de pelo duro)' },
  { name: 'Chow Chow (de pelo suave)' },
  { name: 'Clumber Spaniel' },
  { name: 'Cobrador de Nueva Escocia' },
  { name: 'Cocker spaniel' },
  { name: 'Cocker Spaniel americano' },
  { name: 'Collie barbudo' },
  { name: 'Collie de pelo corto' },
  { name: 'Corgi galés de Cardigan (de pelo medio/largo)' },
  { name: 'Corgi galés de Pembroke' },
  { name: 'Cotón de Tulear' },
  { name: 'Crestado chino' },
  { name: 'Crestado rodesiano (rhodesian ridgeback)' },
  { name: 'Dálmata' },
  { name: 'Dandie Dinmont Terrier' },
  { name: 'Dóberman' },
  { name: 'Dogo de Burdeos' },
  { name: 'Field Spaniel' },
  { name: 'Fox Terrier de pelo duro' },
  { name: 'Fox Terrier de pelo liso' },
  { name: 'Foxhound' },
  { name: 'Galgo' },
  { name: 'Galgo italiano' },
  { name: 'Golden Retriever' },
  { name: 'Gran azul de Gascuña' },
  { name: 'Gran danés' },
  { name: 'Grifón de Bruselas (de pelo corto y duro)' },
  { name: 'Grifón de Bruselas (pelaje corto y áspero)' },
  { name: 'Habanero' },
  { name: 'Hamilton Stovare' },
  { name: 'Hovawart' },
  { name: 'Husky siberiano' },
  { name: 'Keeshond' },
  { name: 'Kerry blue Terrier' },
  { name: 'King Charles Spaniel' },
  { name: 'Komondor' },
  { name: 'Kuvasz húngaro' },
  { name: 'Labrador retriever' },
  { name: 'Laekenois' },
  { name: 'Lakeland Terrier' },
  { name: 'Lancashire Heeler' },
  { name: 'Lebrel escocés' },
  { name: 'Leonberger' },
  { name: 'Lhasa Apso' },
  { name: 'Lobero irlandés' },
  { name: 'Lowchen (pequeño perro león)' },
  { name: 'Malamute de Alaska' },
  { name: 'Maltés' },
  { name: 'Manchester Terrier' },
  { name: 'Mastín inglés o mastiff' },
  { name: 'Mastín napolitano' },
  { name: 'Mastín tibetano' },
  { name: 'Munsterlander (grande)' },
  { name: 'Otterhound' },
  { name: 'Papillón' },
  { name: 'Parson jack russell terrier (de pelo corto/suave)' },
  { name: 'Pastor alemán' },
  { name: 'Pastor australiano' },
  { name: 'Pastor belga Groenendael' },
  { name: 'Pastor belga Malinois' },
  { name: 'Pastor belga Tervueren' },
  { name: 'Pastor de Anatolia' },
  { name: 'Pastor de Brie o Briard' },
  { name: 'Pastor de Los Pirineos' },
  { name: 'Pastor de Maremma' },
  { name: 'Pastor de Shetland (Shetland sheepdog)' },
  { name: 'Pastor ganadero australiano' },
  { name: 'Pastor lapón de Suecia' },
  { name: 'Pastor polaco de las llanuras' },
  { name: 'Perro de agua español' },
  { name: 'Perro de agua irlandés' },
  { name: 'Perro de agua portugués' },
  { name: 'Perro de Canaán' },
  { name: 'Perro de montaña de los Pirineos' },
  { name: 'Perro del faraón' },
  { name: 'Perro finlandés de Laponia' },
  { name: 'Perro Serra da Estrela' },
  { name: 'Pinscher alemán' },
  { name: 'Pinscher miniatura' },
  { name: 'Podenco ibicenco (de pelo corto y liso)' },
  { name: 'Pointer' },
  { name: 'Pomerania' },
  { name: 'Puli húngaro' },
  { name: 'Retriever de Chesapeake' },
  { name: 'Retriever de pelo liso' },
  { name: 'Retriever de pelo rizado' },
  { name: 'Rottweiler' },
  { name: 'Rough Collie o Pastor Escocés' },
  { name: 'Sabueso bávaro de montaña' },
  { name: 'Sabueso italiano (de pelo corto y suave)' },
  { name: 'Saluki (galgo persa)' },
  { name: 'Samoyedo' },
  { name: 'San Bernardo (de pelo medio/largo)' },
  { name: 'Schipperke' },
  { name: 'Schnauzer estándar' },
  { name: 'Schnauzer gigante' },
  { name: 'Schnauzer miniatura' },
  { name: 'Sealyham Terrier' },
  { name: 'Setter escocés' },
  { name: 'Setter inglés' },
  { name: 'Setter irlandés' },
  { name: 'Setter irlandés rojo y blanco' },
  { name: 'Shar Pei' },
  { name: 'Shiba Inu japonés' },
  { name: 'Shih Tzu' },
  { name: 'Silky Terrier australiano' },
  { name: 'Skye Terrier' },
  { name: 'Sloughi (galgo árabe)' },
  { name: 'Soft Coated Wheaten Terrier' },
  { name: 'Spaniel holandés' },
  { name: 'Spaniel tibetano' },
  { name: 'Spinone italiano' },
  { name: 'Spitz alemán mediano' },
  { name: 'Spitz alemán pequeño' },
  { name: 'Spitz finlandés' },
  { name: 'Spitz japonés' },
  { name: 'Springer Spaniel galés' },
  { name: 'Springer spaniel inglés' },
  { name: 'Staffordshire bull terrier' },
  { name: 'Sussex Spaniel' },
  { name: 'Teckel (pelo largo)' },
  { name: 'Teckel de pelo duro' },
  { name: 'Teckel de pelo liso' },
  { name: 'Teckel miniatura de pelo duro' },
  { name: 'Teckel miniatura de pelo largo' },
  { name: 'Teckel miniatura de pelo liso' },
  { name: 'Terranova (Newfoundland)' },
  { name: 'Terrier australiano' },
  { name: 'Terrier Checo' },
  { name: 'Terrier de Airedale' },
  { name: 'Terrier de Norfolk (Norfolk Terrier)' },
  { name: 'Terrier de Norwich (Norwich terrier)' },
  { name: 'Terrier escocés (scottish terrier)' },
  { name: 'Terrier galés' },
  { name: 'Terrier irlandés' },
  { name: 'Terrier tibetano' },
  { name: 'Toy Terrier inglés (negro y fuego)' },
  { name: 'Vallhund sueco' },
  { name: 'West Highland White Terrier' },
  { name: 'Whippet' },
  { name: 'Xoloitzcuintle (mediano)' },
  { name: 'Yorkshire Terrier' },
]

export const catBreeds = [
  { name: 'Abisinio' },
  { name: 'American wirehair (Americano de pelo duro)' },
  { name: 'Asiático' },
  { name: 'Balinés' },
  { name: 'Birmano' },
  { name: 'Bobtail japonés de pelo corto' },
  { name: 'Bobtail japonés de pelo largo' },
  { name: 'Bosque de Noruega' },
  { name: 'Bosque de Siberia' },
  { name: 'Británico de pelo corto' },
  { name: 'Burmilla' },
  { name: 'Chinchilla' },
  { name: 'Cornish rex' },
  { name: 'Cymric' },
  { name: 'Devon rex' },
  { name: 'Exótico de pelo corto' },
  { name: 'Fold escocés' },
  { name: 'Gato azul ruso' },
  { name: 'Gato bengalí' },
  { name: 'Gato bombay' },
  { name: 'Gato burmés' },
  { name: 'Gato egipcio o Sphynx' },
  { name: 'Khao Manee' },
  { name: 'Korat' },
  { name: 'Laperm' },
  { name: 'Maine coon' },
  { name: 'Manx' },
  { name: 'Mau egipcio' },
  { name: 'Mist australiano' },
  { name: 'Munchkin' },
  { name: 'Ocigato' },
  { name: 'Oriental de pelo corto' },
  { name: 'Oriental de pelo largo' },
  { name: 'Persa' },
  { name: 'Pixie bob' },
  { name: 'Ragdoll' },
  { name: 'Savannah' },
  { name: 'Selkirk rex' },
  { name: 'Siamés' },
  { name: 'Singapura' },
  { name: 'Snowshoe' },
  { name: 'Somalí' },
  { name: 'Tiffanie' },
  { name: 'Tonquinés' },
  { name: 'Van turco' },
]
